"""
ELEVENELEVEN — Verified Program Registry

Every entry here has been manually verified as:
  - Pre-revenue friendly (or explicitly idea/early-stage ok)
  - Relevant to a Black female founder in consumer/retail tech
  - An active, recurring program (not a one-time closed grant)

Fields:
  cycle       — "monthly" | "annual" | "biannual" | "rolling" | "summer_2026"
  status      — "open" | "opens_soon" | "closed_check_site" | "always_open"
  amount      — grant/prize value or accelerator terms
  deadline    — ISO date if known, None if rolling
  verified_on — date this entry was last manually checked
  scrape_url  — page to scrape for deadline updates (None if rolling/known)
"""

PROGRAMS = [

    # ══════════════════════════════════════════════════════════════════
    # ALWAYS OPEN — Apply any time
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "Amber Grant (Monthly Startup Grant)",
        "url": "https://ambergrantsforwomen.com/get-an-amber-grant/",
        "type": "grant",
        "tags": ["women founder", "startup", "monthly", "no-equity", "pre-revenue ok"],
        "cycle": "monthly",
        "status": "always_open",
        "amount": "$10,000/month + $50,000 year-end",
        "deadline": None,
        "notes": "Rolling monthly. $15 application fee. Startup-specific tier for businesses with <$10K revenue. US/Canada only. Apply once, considered for all categories.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://ambergrantsforwomen.com/get-an-amber-grant/",
    },
    {
        "name": "HerRise MicroGrant",
        "url": "https://www.helloalice.com/grants/",
        "type": "grant",
        "tags": ["women founder", "women of color", "monthly", "no-equity", "pre-revenue ok"],
        "cycle": "monthly",
        "status": "always_open",
        "amount": "$1,000/month",
        "deadline": None,
        "notes": "Awarded monthly. Women-owned business, <$1M revenue. Last day of each month deadline. Via Hello Alice.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": None,
    },
    {
        "name": "Hello Alice Grant Feed",
        "url": "https://helloalice.com/grants/",
        "type": "grant_aggregator",
        "tags": ["women founder", "diverse founder", "aggregator", "pre-revenue ok"],
        "cycle": "rolling",
        "status": "always_open",
        "amount": "varies",
        "deadline": None,
        "notes": "Active aggregator of currently open grants. Check weekly for new listings.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://helloalice.com/grants/",
    },
    {
        "name": "IFundWomen Grant Database",
        "url": "https://ifundwomen.com/grants",
        "type": "grant_aggregator",
        "tags": ["women founder", "aggregator", "rolling", "pre-revenue ok"],
        "cycle": "rolling",
        "status": "always_open",
        "amount": "varies",
        "deadline": None,
        "notes": "Live database of open grants for women founders. New listings added regularly.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://ifundwomen.com/grants",
    },

    # ══════════════════════════════════════════════════════════════════
    # CURRENTLY OPEN (as of June 2026)
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "Y Combinator Fall 2026 Batch",
        "url": "https://www.ycombinator.com/apply",
        "type": "accelerator",
        "tags": ["top-tier", "consumer", "tech", "pre-revenue ok", "pre-seed"],
        "cycle": "biannual",
        "status": "open",
        "amount": "$500K for 7% equity (standard YC terms)",
        "deadline": "2026-07-27",
        "notes": "Pre-revenue explicitly ok. Solo founders accepted. Must attend in-person in SF. One of the best signals for future fundraising.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.ycombinator.com/apply",
    },
    {
        "name": "Visionaries Pitch Competition",
        "url": "https://www.ifundwomen.com/visionaries",
        "type": "competition",
        "tags": ["women founder", "pitch", "no-equity", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "$40,000 grant",
        "deadline": "2026-06-18",
        "notes": "Women-owned, US-based, for-profit. Closes June 18, 2026 — APPLY NOW.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": None,
    },
    {
        "name": "NAACP Powershift Entrepreneur Grant",
        "url": "https://naacp.org/find-resources/grants",
        "type": "grant",
        "tags": ["Black founder", "grant", "no-equity", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "$25,000",
        "deadline": None,
        "notes": "For Black entrepreneurs. Check naacp.org for current cycle deadline.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://naacp.org/find-resources/grants",
    },
    {
        "name": "SoGal Foundation Black Founder Startup Grant",
        "url": "https://sogalfoundation.com",
        "type": "grant",
        "tags": ["Black founder", "women founder", "grant", "no-equity", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "$5,000–$10,000",
        "deadline": None,
        "notes": "For Black women and nonbinary entrepreneurs. Registered business required. Check site for current deadline.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://sogalfoundation.com",
    },
    {
        "name": "Google for Startups Women Founders Fund",
        "url": "https://startup.google.com/programs/women-founders-fund/",
        "type": "grant",
        "tags": ["women founder", "tech", "no-equity", "consumer"],
        "cycle": "annual",
        "status": "open",
        "amount": "Up to $100,000 non-dilutive + Google Cloud credits",
        "deadline": None,
        "notes": "Requires at least one woman founder. Tech-focused. High-value non-dilutive. Check site for open cycle.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://startup.google.com/programs/women-founders-fund/",
    },
    {
        "name": "Black Girl Ventures Pitch",
        "url": "https://www.blackgirlventures.org/bgv-pitch",
        "type": "competition",
        "tags": ["Black women founder", "pitch", "consumer", "community"],
        "cycle": "rolling",
        "status": "open",
        "amount": "Up to $15,000 (1st place)",
        "deadline": None,
        "notes": "City-based pitch competitions (NYC, LA, Chicago, Austin). Requires some revenue but under $1M. Check site for next city event.",
        "pre_revenue_ok": False,
        "verified_on": "2026-06-08",
        "scrape_url": "https://blackgirlventures.submittable.com/submit",
    },
    {
        "name": "Fearless Fund Grants",
        "url": "https://fearlessfund.com/grants/",
        "type": "grant",
        "tags": ["Black women founder", "consumer", "retail", "grant"],
        "cycle": "annual",
        "status": "open",
        "amount": "$20,000",
        "deadline": None,
        "notes": "For Black women entrepreneurs in the US. Check site for current open cycle.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://fearlessfund.com/grants/",
    },
    {
        "name": "The Doonie Fund",
        "url": "https://www.thedooniefund.org",
        "type": "grant",
        "tags": ["Black women founder", "grant", "no-equity", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "varies",
        "deadline": None,
        "notes": "Grants specifically for Black women entrepreneurs. Check site for open cycle.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.thedooniefund.org",
    },

    # ══════════════════════════════════════════════════════════════════
    # OPENS SOON / WATCH THESE
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "Camelback Ventures Fellowship",
        "url": "https://www.camelbackventures.org/apply/",
        "type": "fellowship",
        "tags": ["Black founder", "women founder", "fellowship", "pre-revenue ok", "early-stage"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "$5,000 grant + coaching + capital connections",
        "deadline": None,
        "notes": "2026 cycle closed March 2. Reopens Summer 2026 — set a reminder to check in July.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.camelbackventures.org/apply/",
    },
    {
        "name": "MassChallenge US Early Stage",
        "url": "https://masschallenge.org/united-states-early-stage/",
        "type": "accelerator",
        "tags": ["Boston", "no equity", "pre-revenue ok", "early-stage"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "Up to $100,000 equity-free cash prizes",
        "deadline": None,
        "notes": "2026 cycle closed March 4. Zero equity, zero fees. Watch for 2027 cycle opening ~Jan 2027.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://masschallenge.org/programs-all/",
    },
    {
        "name": "digitalundivided Breakthrough",
        "url": "https://www.digitalundivided.com/programs",
        "type": "accelerator",
        "tags": ["Black founder", "Latinx founder", "women founder", "tech", "pre-revenue ok"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "$5,000 + education resources",
        "deadline": None,
        "notes": "For Black and Latinx women entrepreneurs. Check site for next cycle.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.digitalundivided.com/programs",
    },
    {
        "name": "Tory Burch Foundation Fellows",
        "url": "https://www.toryburchfoundation.org/resources/fellows-program/",
        "type": "fellowship",
        "tags": ["women founder", "consumer", "retail", "fellowship", "pre-revenue ok"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "Fellowship + funding access + network",
        "deadline": None,
        "notes": "Prestigious fellowship for women in consumer/retail. Typically opens fall. Watch for 2027 cycle.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.toryburchfoundation.org/resources/fellows-program/",
    },

    # ══════════════════════════════════════════════════════════════════
    # HBS / HARVARD — insider access as a student
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "HBS Rock Venture Catalyst",
        "url": "https://www.hbs.edu/entrepreneurship/programs/Pages/default.aspx",
        "type": "accelerator",
        "tags": ["HBS", "student founder", "summer", "pre-revenue ok"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "Funding + structured mentorship (amount varies by cohort)",
        "deadline": None,
        "notes": "HBS summer program for MBA student founders. 2026 cohort selected. Watch for 2027 cycle opening ~Jan.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.hbs.edu/entrepreneurship/programs/Pages/default.aspx",
    },
    {
        "name": "HBS New Venture Competition",
        "url": "https://www.hbs.edu/newventurecompetition",
        "type": "competition",
        "tags": ["HBS", "competition", "prize", "pre-revenue ok"],
        "cycle": "annual",
        "status": "opens_soon",
        "amount": "Up to $75,000",
        "deadline": None,
        "notes": "2026 cycle complete. Watch for 2027 opening ~September. As an HBS student this is a must-enter.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.hbs.edu/newventurecompetition",
    },
    {
        "name": "Harvard Innovation Labs Funding",
        "url": "https://innovationlabs.harvard.edu/resources/funding-opportunities",
        "type": "grant",
        "tags": ["Harvard", "student founder", "pre-revenue ok", "rolling"],
        "cycle": "rolling",
        "status": "always_open",
        "amount": "varies by program",
        "deadline": None,
        "notes": "Multiple funding streams for Harvard student founders. Check regularly — new opportunities posted throughout year.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://innovationlabs.harvard.edu/resources/funding-opportunities",
    },

    # ══════════════════════════════════════════════════════════════════
    # CONSUMER / RETAIL TECH SPECIFIC
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "XRC Ventures Retail Accelerator",
        "url": "https://www.xrcventures.com",
        "type": "accelerator",
        "tags": ["retail tech", "consumer tech", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "Investment + mentorship (terms vary)",
        "deadline": None,
        "notes": "Top-ranked US accelerator focused on retail/consumer tech intersection. Check site for 2026 cohort.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.xrcventures.com",
    },
    {
        "name": "Techstars (open programs)",
        "url": "https://www.techstars.com/accelerators",
        "type": "accelerator",
        "tags": ["consumer", "retail tech", "top-tier", "pre-revenue ok"],
        "cycle": "rolling",
        "status": "open",
        "amount": "$120K for 6% equity (standard terms)",
        "deadline": "2026-06-10",
        "notes": "Multiple cohorts open. Final deadlines approaching June 10. Filter by consumer/retail programs.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://www.techstars.com/accelerators",
    },
    {
        "name": "LVMH La Maison des Startups",
        "url": "https://lamaisondesstartups.lvmh.com",
        "type": "accelerator",
        "tags": ["consumer", "retail", "luxury", "fashion", "pre-revenue ok"],
        "cycle": "annual",
        "status": "open",
        "amount": "No equity — mentorship + LVMH network access",
        "deadline": None,
        "notes": "For consumer/retail/luxury tech startups. Strong network value even without cash.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://lamaisondesstartups.lvmh.com",
    },
    {
        "name": "f.inc Programs",
        "url": "https://f.inc",
        "type": "accelerator",
        "tags": ["pre-revenue ok", "consumer", "tech", "early-stage"],
        "cycle": "rolling",
        "status": "open",
        "amount": "varies by program",
        "deadline": None,
        "notes": "Runs cohort programs including Canopy. Check for open applications.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": "https://f.inc",
    },

    # ══════════════════════════════════════════════════════════════════
    # INVESTMENT (pre-seed, pre-revenue friendly)
    # ══════════════════════════════════════════════════════════════════

    {
        "name": "Backstage Capital",
        "url": "https://backstagecapital.com",
        "type": "investment",
        "tags": ["underrepresented founder", "Black founder", "women founder", "pre-seed"],
        "cycle": "rolling",
        "status": "open",
        "amount": "$25K–$500K pre-seed investment",
        "deadline": None,
        "notes": "Invests in underrepresented founders. Pre-revenue ok. Rolling applications.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": None,
    },
    {
        "name": "Harlem Capital",
        "url": "https://harlemcapital.co/apply",
        "type": "investment",
        "tags": ["Black founder", "diverse founder", "consumer", "pre-seed"],
        "cycle": "rolling",
        "status": "open",
        "amount": "Pre-seed / seed investment",
        "deadline": None,
        "notes": "Focuses on diverse founders. Consumer-friendly. Rolling intake.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": None,
    },
    {
        "name": "Overlooked Ventures",
        "url": "https://www.overlooked.vc",
        "type": "investment",
        "tags": ["Black founder", "women founder", "pre-seed", "pre-revenue ok"],
        "cycle": "rolling",
        "status": "open",
        "amount": "Pre-seed investment",
        "deadline": None,
        "notes": "Explicitly focused on overlooked founders. Pre-revenue ok.",
        "pre_revenue_ok": True,
        "verified_on": "2026-06-08",
        "scrape_url": None,
    },
]

# Subsets for convenience
OPEN_NOW = [p for p in PROGRAMS if p["status"] in ("open", "always_open")]
OPENS_SOON = [p for p in PROGRAMS if p["status"] == "opens_soon"]
PRE_REVENUE = [p for p in PROGRAMS if p.get("pre_revenue_ok", False)]
